/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import * as path from 'node:path';
import * as fs from 'node:fs';
import * as crypto from 'node:crypto';
import { copyDirRecursive, extractKitDescription } from './init-templates';
import { discoverPlaceholders } from './init-placeholders';
import { resolveAssetDir } from './resolve-asset-dir';
import { cliCommandForVersion } from './init-version';
import { GeneratedFileManifest } from './init-types';

export { GeneratedFileManifest };

/** A file MDAA generates: where it goes relative to the project root, and its content */
export interface GeneratedFile {
  readonly relativePath: string;
  readonly content: string;
}

/** Manifest to record in, plus the overwrite policy for user-modified files */
export interface WriteOptions {
  readonly manifest: GeneratedFileManifest;
  /** Overwrite a modified file without asking */
  readonly overwrite: boolean;
  /** Never block on input: a modified file is left alone rather than prompted for */
  readonly noPrompt: boolean;
}

/** Everything {@link generateSteeringFiles} needs, as one bag to keep the arity down */
export interface SteeringOptions extends WriteOptions {
  readonly kitName?: string;
  readonly version?: string;
}

function sha256(content: string): string {
  return crypto.createHash('sha256').update(content).digest('hex');
}

/**
 * Write a file MDAA generates, tracking its content hash in the manifest.
 *
 * - Doesn't exist yet -> write it, record the hash.
 * - Exists and its hash matches what's recorded -> unmodified since MDAA last
 *   wrote it -> safe to overwrite silently, refresh the hash.
 * - Exists and the hash differs (or was never recorded) -> either the user
 *   edited it, or it pre-dates MDAA entirely -> prompt for confirmation unless
 *   `overwrite` is set.
 */
export function writeGeneratedFile(outputDir: string, file: GeneratedFile, options: WriteOptions): void {
  const { relativePath, content } = file;
  const { manifest, overwrite, noPrompt } = options;
  const filePath = path.join(outputDir, relativePath);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const newHash = sha256(content);
  // `.mdaa/metadata.json` is committed and read on other machines, so its keys must not
  // carry the writing platform's separator: a manifest written on Windows would miss every
  // lookup on macOS, making every file look "modified" and firing the prompt on each run.
  const manifestKey = relativePath.split(path.sep).join('/');

  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, content);
    manifest[manifestKey] = newHash;
    return;
  }

  const currentHash = sha256(fs.readFileSync(filePath, 'utf-8'));
  const recordedHash = manifest[manifestKey];

  if (overwrite || currentHash === recordedHash) {
    fs.writeFileSync(filePath, content);
    manifest[manifestKey] = newHash;
    return;
  }

  if (noPrompt) {
    // --no-prompt means "never block on input", so a modified user-owned file is left as
    // it is. Previously the flag never reached here and the prompt blocked anyway.
    console.log(`  Skipped: ${manifestKey} (modified since generated; --no-prompt)`);
    return;
  }

  if (promptOverwrite(manifestKey, recordedHash !== undefined)) {
    fs.writeFileSync(filePath, content);
    manifest[manifestKey] = newHash;
  } else {
    console.log(`  Skipped: ${manifestKey}`);
  }
}

/** Prompt via inherited stdio; returns false (skip) in non-interactive environments */
function promptOverwrite(relativePath: string, wasModifiedSinceGenerated: boolean): boolean {
  const reason = wasModifiedSinceGenerated
    ? 'was modified since it was generated'
    : 'already exists (not generated by a previous mdaa init/enhance)';
  process.stdout.write(`  ${relativePath} ${reason}. Overwrite? [y/N] `);
  try {
    // Read a whole line, not 4 bytes: `yes` in a 4-byte buffer used to arrive as "yes"
    // (treated as no) and leave residue that desynchronised the next prompt.
    const answer = readLineFromStdin();
    return answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes';
  } catch (err) {
    // `prompts` leaves stdin in non-blocking mode, so an interactive terminal can raise
    // EAGAIN here. Treating that as "non-interactive" silently skipped a file the user
    // was never actually asked about, so it is reported distinctly.
    if ((err as { code?: string }).code === 'EAGAIN') {
      console.log('  (could not read a response — skipping, re-run with --overwrite to overwrite)');
    } else {
      console.log('  (non-interactive — skipping)');
    }
    return false;
  }
}

/** Read one line from fd 0, growing past a single read so long answers arrive intact */
function readLineFromStdin(): string {
  const chunks: Buffer[] = [];
  const buf = Buffer.alloc(64);
  for (;;) {
    const bytesRead = fs.readSync(0, buf, 0, buf.length, null);
    if (bytesRead === 0) break; // EOF
    const chunk = buf.subarray(0, bytesRead);
    chunks.push(Buffer.from(chunk));
    if (chunk.includes(0x0a)) break; // newline — the answer is complete
  }
  return Buffer.concat(chunks).toString().trim();
}

export function getDocsDir(): string {
  const pkgDir = resolveAssetDir({
    packageName: '@aws-mdaa/init-assets',
    marker: 'docs',
  });
  return pkgDir ? path.join(pkgDir, 'docs') : '';
}

/** Resolve the @aws-mdaa/init-assets steering directory, or '' if unavailable */
export function getInitAssetsSteeringDir(): string {
  const pkgDir = resolveAssetDir({
    packageName: '@aws-mdaa/init-assets',
    marker: 'steering',
  });
  return pkgDir ? path.join(pkgDir, 'steering') : '';
}

/**
 * Read the canonical rule body that the per-tool projections reference,
 * preferring init-assets over the repo tree. The projections point at
 * `agent_rules/<name>.md` in the consumer project, so mdaa init copies this
 * body there (with references rewritten to the versioned asset paths).
 */
export function getCanonicalRule(fileName: string): string {
  const steeringDir = getInitAssetsSteeringDir();
  if (steeringDir) {
    const bundled = path.join(steeringDir, 'canonical', fileName);
    if (fs.existsSync(bundled)) return fs.readFileSync(bundled, 'utf-8');
  }

  const repoRoot = path.join(__dirname, '..', '..', '..');
  const repoFile = path.join(repoRoot, 'agent_rules', fileName);
  if (fs.existsSync(repoFile)) return fs.readFileSync(repoFile, 'utf-8');

  return '';
}

/**
 * Rewrite a canonical rule's repo-root-relative references to the versioned
 * paths where mdaa init places those assets in the consumer project:
 *   CONFIGURATION.md      -> .mdaa/<version>/docs/CONFIGURATION.md
 *   schemas/@aws-mdaa/    -> .mdaa/<version>/schemas/@aws-mdaa/
 *
 * Only the bare reference is replaced, so anything preceding it is left in place
 * and a `../` prefix carries through: `../CONFIGURATION.md` becomes
 * `../.mdaa/<version>/docs/CONFIGURATION.md`. Both forms occur in the same body
 * and need that difference — the body lands at `agent_rules/<name>.md`, so its
 * markdown links resolve one directory below the project root and have to climb
 * out, while Kiro's `#[[file:...]]` includes are workspace-root-relative and
 * carry no prefix.
 */
export function rewriteCanonicalReferences(body: string, version: string): string {
  // Without a version there is no `.mdaa/<version>/` to point at, and rewriting anyway
  // would emit `.mdaa//docs/...`. Leaving the references alone is the lesser wrong.
  if (!version) return body;
  return body
    .split('CONFIGURATION.md')
    .join(`.mdaa/${version}/docs/CONFIGURATION.md`)
    .split('schemas/@aws-mdaa/')
    .join(`.mdaa/${version}/schemas/@aws-mdaa/`);
}

/** Copy README and sample_configs for a single module app */
export function copyModuleAppDocs(
  appsDir: string,
  app: { categoryName: string; appName: string },
  docsDestDir: string,
): void {
  const { categoryName, appName } = app;
  const appReadme = path.join(appsDir, categoryName, appName, 'README.md');
  if (!fs.existsSync(appReadme)) return;
  const destDir = path.join(docsDestDir, 'packages', 'apps', categoryName, appName);
  fs.mkdirSync(destDir, { recursive: true });
  fs.copyFileSync(appReadme, path.join(destDir, 'README.md'));

  const sampleConfigsDir = path.join(appsDir, categoryName, appName, 'sample_configs');
  if (fs.existsSync(sampleConfigsDir)) {
    copyDirRecursive(sampleConfigsDir, path.join(destDir, 'sample_configs'));
  }
}

export function copyRepoDirectDocs(docsDestDir: string): void {
  const repoRoot = path.join(__dirname, '..', '..', '..');
  const readmeSrc = path.join(repoRoot, 'README.md');
  const configSrc = path.join(repoRoot, 'CONFIGURATION.md');

  if (fs.existsSync(readmeSrc)) {
    fs.copyFileSync(readmeSrc, path.join(docsDestDir, 'README.md'));
  }
  if (fs.existsSync(configSrc)) {
    fs.copyFileSync(configSrc, path.join(docsDestDir, 'CONFIGURATION.md'));
  }

  const appsDir = path.join(repoRoot, 'packages', 'apps');
  if (!fs.existsSync(appsDir)) return;

  // Mirror repo structure: packages/apps/<category>/<module>-app/README.md
  const categories = fs.readdirSync(appsDir, { withFileTypes: true });
  for (const category of categories) {
    if (!category.isDirectory()) continue;
    const categoryDir = path.join(appsDir, category.name);
    const apps = fs.readdirSync(categoryDir, { withFileTypes: true });
    for (const app of apps) {
      if (!app.isDirectory() || !app.name.endsWith('-app')) continue;
      copyModuleAppDocs(appsDir, { categoryName: category.name, appName: app.name }, docsDestDir);
    }
  }
}

/** Opening lines: the kit's own description, or a generic one for an enhanced project */
function introLines(outputDir: string, kitName?: string): string[] {
  if (!kitName) {
    return [
      'This is an MDAA (Modern Data Architecture Accelerator) configuration project.',
      'It defines AWS infrastructure as YAML config files deployed via the MDAA CLI.',
      '',
    ];
  }
  const kitDescription = extractKitDescription(outputDir);
  return [
    ...(kitDescription ? [kitDescription, ''] : []),
    `Starter kit: \`${kitName}\``,
    `Kit docs: https://aws.github.io/modern-data-architecture-accelerator/starter_kits/${kitName}/`,
    '',
  ];
}

/** The outstanding `<YOUR_...>` placeholders, and how the agent should help fill them */
function todoLines(outputDir: string): string[] {
  const placeholders = discoverPlaceholders(outputDir);
  if (placeholders.length === 0) return [];

  return [
    '## Outstanding TODOs',
    '',
    'The following placeholders need values before deployment:',
    '',
    ...placeholders.map(({ placeholder, description }) => {
      const suffix = description ? ` — ${description}` : '';
      return `- \`${placeholder}\`${suffix}`;
    }),
    '',
    'When the user asks for help, walk them through each placeholder explaining what value is needed.',
    'For CDK Nag suppressions (commented out in roles configs), explain what permissions each allows',
    'and help the user decide whether to uncomment it.',
    '',
  ];
}

/** Generate project-specific getting-started content based on the output directory state */
export function generateGettingStartedContent(outputDir: string, kitName?: string, version?: string): string {
  const docsPath = version ? `.mdaa/${version}/docs` : 'docs/mdaa';
  const schemasPath = version ? `.mdaa/${version}/schemas` : 'schemas';
  const cli = cliCommandForVersion(version);
  const lines: string[] = [
    '# MDAA Project — Getting Started',
    '',
    ...introLines(outputDir, kitName),
    ...todoLines(outputDir),
  ];

  // Deployment readiness and extending
  lines.push(
    '## Deployment',
    '',
    'Validate before deploying:',
    `- \`${cli} synth\` — synthesize templates (catches config errors without deploying)`,
    `- \`${cli} ls\` — list stacks that will be deployed`,
    '',
    'Deploy:',
    `- \`${cli} deploy\` — deploy all modules`,
    '',
    '## Adding New Modules',
    '',
    `To add a new capability, consult \`${docsPath}/README.md\` for the module catalog.`,
    'Each module has a README with deployed resources and sample configs at',
    `\`${docsPath}/packages/apps/<category>/<module-name>-app/\`.`,
    `Start new configs from \`sample_configs/sample-config-minimal.yaml\`. Schemas are at \`${schemasPath}/@aws-mdaa/<module-name>.json\`.`,
    '',
  );

  return lines.join('\n');
}

/**
 * Generate AI steering/instruction files for Kiro, Claude Code, and GitHub
 * Copilot. Every write goes through {@link writeGeneratedFile}, which tracks
 * a content hash in `manifest` so a later run can tell whether the user
 * edited a file since MDAA last wrote it — and prompts (unless `overwrite`)
 * rather than silently clobbering it.
 */
export function generateSteeringFiles(outputDir: string, options: SteeringOptions): void {
  const { kitName, version } = options;
  // Both project-root agent_rules/ bodies follow the same pattern: a canonical
  // body referenced by thin per-tool frontmatter wrappers. getting-started is
  // generated per-project; user-config-authoring is copied from the package.

  // getting-started body (always-loaded), generated dynamically
  const gettingStarted = generateGettingStartedContent(outputDir, kitName, version);
  writeGeneratedFile(outputDir, { relativePath: 'agent_rules/getting-started.md', content: gettingStarted }, options);

  // user-config-authoring body (fileMatch-scoped), copied from package with
  // repo-root-relative references rewritten to versioned .mdaa/<version>/ paths.
  // The per-tool wrappers below reference this file unconditionally, so a bundling miss
  // that left it out would produce steering files pointing at a file that was never
  // written — fail instead of generating that dangling set.
  const canonical = getCanonicalRule('user-config-authoring.md');
  if (!canonical) {
    throw new Error(
      'Canonical rule user-config-authoring.md not found. Install @aws-mdaa/init-assets or run from the MDAA repo root.',
    );
  }
  writeGeneratedFile(
    outputDir,
    {
      relativePath: 'agent_rules/user-config-authoring.md',
      content: rewriteCanonicalReferences(canonical, version ?? ''),
    },
    options,
  );

  writeKiroWrappers(outputDir, options);
  writeClaudeWrappers(outputDir, options);
  writeCopilotWrappers(outputDir, options);
}

/**
 * Kiro: thin wrappers under .kiro/steering/ that reference the bodies in
 * agent_rules/ via #[[file:...]] include directives (workspace-root-relative).
 */
export function writeKiroWrappers(outputDir: string, options: WriteOptions): void {
  writeGeneratedFile(
    outputDir,
    {
      relativePath: path.join('.kiro', 'steering', 'getting-started.md'),
      content: ['---', 'inclusion: always', '---', '', '#[[file:agent_rules/getting-started.md]]', ''].join('\n'),
    },
    options,
  );
  writeGeneratedFile(
    outputDir,
    {
      relativePath: path.join('.kiro', 'steering', 'user-config-authoring.md'),
      content: [
        '---',
        'inclusion: fileMatch',
        "fileMatchPattern: '**/*.yaml,**/*.yml'",
        '---',
        '',
        '#[[file:agent_rules/user-config-authoring.md]]',
        '',
      ].join('\n'),
    },
    options,
  );
}

/**
 * Claude Code: the always-loaded getting-started goes to the root CLAUDE.md
 * (auto-loaded); the fileMatch user-config-authoring goes to .claude/rules/.
 * Both reference the bodies in agent_rules/ via relative Markdown links.
 */
export function writeClaudeWrappers(outputDir: string, options: WriteOptions): void {
  // Root CLAUDE.md -> agent_rules/getting-started.md (sibling of root)
  writeGeneratedFile(
    outputDir,
    {
      relativePath: 'CLAUDE.md',
      content: ['# MDAA Agent Rules', '', 'See [`getting-started`](agent_rules/getting-started.md)', ''].join('\n'),
    },
    options,
  );

  // .claude/rules/ is two levels deep -> ../../agent_rules/
  writeGeneratedFile(
    outputDir,
    {
      relativePath: path.join('.claude', 'rules', 'user-config-authoring.md'),
      content: [
        '<!-- scope: fileMatch | globs: **/*.yaml, **/*.yml -->',
        '',
        'See [`user-config-authoring`](../../agent_rules/user-config-authoring.md)',
        '',
      ].join('\n'),
    },
    options,
  );
}

/**
 * GitHub Copilot: always-loaded getting-started goes to the root
 * .github/copilot-instructions.md; the fileMatch user-config-authoring goes to
 * .github/instructions/ with an applyTo glob. Both reference agent_rules/.
 */
export function writeCopilotWrappers(outputDir: string, options: WriteOptions): void {
  // .github/copilot-instructions.md is one level deep -> ../agent_rules/
  writeGeneratedFile(
    outputDir,
    {
      relativePath: path.join('.github', 'copilot-instructions.md'),
      content: ['# MDAA Agent Rules', '', 'See [`getting-started`](../agent_rules/getting-started.md)', ''].join('\n'),
    },
    options,
  );

  // .github/instructions/ is two levels deep -> ../../agent_rules/
  writeGeneratedFile(
    outputDir,
    {
      relativePath: path.join('.github', 'instructions', 'user-config-authoring.instructions.md'),
      content: [
        "---\napplyTo: '**/*.yaml,**/*.yml'\n---",
        '',
        'See [`user-config-authoring`](../../agent_rules/user-config-authoring.md)',
        '',
      ].join('\n'),
    },
    options,
  );
}
