/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import { MdaaConstructProps } from '@aws-mdaa/construct'; //NOSONAR
import { MdaaRole, MdaaRoleProps, IMdaaRole } from '@aws-mdaa/iam-constructs';
import { Duration, Stack } from 'aws-cdk-lib';
import { IManagedPolicy, PolicyDocument, PolicyStatement, ServicePrincipal } from 'aws-cdk-lib/aws-iam';
import { MdaaNagSuppressions } from '@aws-mdaa/construct'; //NOSONAR
import { Construct } from 'constructs';

export interface MdaaLambdaRoleProps extends MdaaConstructProps {
  readonly logGroupNames?: string[];
  readonly externalIds?: string[];
  readonly managedPolicies?: IManagedPolicy[];
  readonly inlinePolicies?: {
    [name: string]: PolicyDocument;
  };
  /** IAM path for Lambda role organization and management enabling hierarchical role structure */
  readonly path?: string;
  readonly permissionsBoundary?: IManagedPolicy;
  readonly roleName: string;
  readonly maxSessionDuration?: Duration;
  /** Description for the Lambda execution role enabling role documentation and management clarity */
  readonly description?: string;
}

export type IMdaaLambdaRole = IMdaaRole;

export class MdaaLambdaRole extends MdaaRole {
  private static setLambdaProps(props: MdaaLambdaRoleProps): MdaaRoleProps {
    const overrideProps = {
      assumedBy: new ServicePrincipal('lambda.amazonaws.com'),
    };
    return { ...props, ...overrideProps };
  }

  constructor(scope: Construct, id: string, props: MdaaLambdaRoleProps) {
    super(scope, id, MdaaLambdaRole.setLambdaProps(props));

    if (props.logGroupNames) {
      this.addLogGroups(props.logGroupNames);
    }
  }
  private addLogGroups(logGroupNames: string[]) {
    const logGroupArns = logGroupNames.map(
      logGroup => `arn:${Stack.of(this).partition}:logs:*:*:log-group:/aws/lambda/${logGroup}*`,
    );
    const logStreamStatement = new PolicyStatement({
      resources: logGroupArns,
      actions: ['logs:PutLogEvents', 'logs:CreateLogStream'],
    });
    this.addToPolicy(logStreamStatement);
    const logGroupStatement = new PolicyStatement({
      resources: logGroupArns,
      actions: ['logs:CreateLogGroup'],
    });
    this.addToPolicy(logGroupStatement);
    MdaaNagSuppressions.addCodeResourceSuppressions(
      this,
      [
        {
          id: 'AwsSolutions-IAM5',
          reason: 'LogStream names dynamically generated by Lambda. Wildcard limited to log stream name.',
        },
        {
          id: 'NIST.800.53.R5-IAMNoInlinePolicy',
          reason: 'Inline policy is specific to this role and its custom resource.',
        },
        {
          id: 'HIPAA.Security-IAMNoInlinePolicy',
          reason: 'Inline policy is specific to this role and its custom resource.',
        },
        {
          id: 'PCI.DSS.321-IAMNoInlinePolicy',
          reason: 'Inline policy is specific to this role and its custom resource.',
        },
      ],
      true,
    );
  }
}
