/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Direct coverage for the overwrite protection.
 *
 * Every `runInit` call in `mdaa-init.test.ts` passes `force: true`, which short-circuits
 * the whole manifest comparison — so the SHA-256 hashing, the modified-since-generated
 * detection, the prompt, and the skip path were never executed by any test. These exercise
 * `writeGeneratedFile` directly, with `force: false`.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import * as crypto from 'node:crypto';
import { writeGeneratedFile, GeneratedFileManifest } from '../lib/init-steering';

const sha256 = (content: string): string => crypto.createHash('sha256').update(content).digest('hex');

describe('writeGeneratedFile', () => {
  let outputDir: string;

  beforeEach(() => {
    outputDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mdaa-write-generated-'));
  });

  afterEach(() => {
    jest.restoreAllMocks();
    fs.rmSync(outputDir, { recursive: true, force: true });
  });

  const file = (relativePath: string, content: string) => ({ relativePath, content });

  test('writes a new file and records its hash', () => {
    const manifest: GeneratedFileManifest = {};

    writeGeneratedFile(outputDir, file('agent_rules/getting-started.md', 'body\n'), {
      manifest,
      force: false,
      noPrompt: false,
    });

    expect(fs.readFileSync(path.join(outputDir, 'agent_rules', 'getting-started.md'), 'utf-8')).toEqual('body\n');
    expect(manifest['agent_rules/getting-started.md']).toEqual(sha256('body\n'));
  });

  test('overwrites silently when the file is unmodified since MDAA wrote it', () => {
    const target = path.join(outputDir, 'CLAUDE.md');
    fs.writeFileSync(target, 'generated v1\n');
    const manifest: GeneratedFileManifest = { 'CLAUDE.md': sha256('generated v1\n') };
    const readSync = jest.spyOn(fs, 'readSync');

    writeGeneratedFile(outputDir, file('CLAUDE.md', 'generated v2\n'), { manifest, force: false, noPrompt: false });

    expect(fs.readFileSync(target, 'utf-8')).toEqual('generated v2\n');
    expect(manifest['CLAUDE.md']).toEqual(sha256('generated v2\n'));
    // No prompt: an unmodified file needs no confirmation
    expect(readSync).not.toHaveBeenCalled();
  });

  test('leaves a user-modified file alone when the prompt is declined', () => {
    const target = path.join(outputDir, 'CLAUDE.md');
    fs.writeFileSync(target, 'MY EDITS\n');
    const manifest: GeneratedFileManifest = { 'CLAUDE.md': sha256('generated v1\n') };
    jest.spyOn(fs, 'readSync').mockImplementation(((_fd: number, buf: Buffer) => {
      buf.write('n\n');
      return 2;
    }) as typeof fs.readSync);

    writeGeneratedFile(outputDir, file('CLAUDE.md', 'generated v2\n'), { manifest, force: false, noPrompt: false });

    expect(fs.readFileSync(target, 'utf-8')).toEqual('MY EDITS\n');
    // The recorded hash must not advance, or the next run would treat the edits as MDAA's
    expect(manifest['CLAUDE.md']).toEqual(sha256('generated v1\n'));
  });

  test('accepts `yes`, not just `y`', () => {
    const target = path.join(outputDir, 'CLAUDE.md');
    fs.writeFileSync(target, 'MY EDITS\n');
    const manifest: GeneratedFileManifest = { 'CLAUDE.md': sha256('generated v1\n') };
    // A 4-byte buffer truncated this to "yes" with residue left on stdin, and "yes" was
    // then compared against "y" and treated as no.
    jest.spyOn(fs, 'readSync').mockImplementation(((_fd: number, buf: Buffer) => {
      buf.write('yes\n');
      return 4;
    }) as typeof fs.readSync);

    writeGeneratedFile(outputDir, file('CLAUDE.md', 'generated v2\n'), { manifest, force: false, noPrompt: false });

    expect(fs.readFileSync(target, 'utf-8')).toEqual('generated v2\n');
  });

  test('prompts for a foreign file that MDAA never generated', () => {
    const target = path.join(outputDir, 'CLAUDE.md');
    fs.writeFileSync(target, 'PRE-EXISTING TEAM FILE\n');
    const writes: string[] = [];
    jest.spyOn(process.stdout, 'write').mockImplementation(((chunk: string) => {
      writes.push(String(chunk));
      return true;
    }) as typeof process.stdout.write);
    jest.spyOn(fs, 'readSync').mockImplementation(() => 0); // EOF -> declined

    // Empty manifest: the file predates MDAA entirely
    writeGeneratedFile(outputDir, file('CLAUDE.md', 'generated\n'), { manifest: {}, force: false, noPrompt: false });

    expect(fs.readFileSync(target, 'utf-8')).toEqual('PRE-EXISTING TEAM FILE\n');
    expect(writes.join('')).toContain('already exists (not generated by a previous mdaa init/enhance)');
  });

  test('leaves a user-modified file alone under --no-prompt, without reading stdin', () => {
    const target = path.join(outputDir, 'CLAUDE.md');
    fs.writeFileSync(target, 'MY EDITS\n');
    const readSync = jest.spyOn(fs, 'readSync');

    writeGeneratedFile(outputDir, file('CLAUDE.md', 'generated\n'), { manifest: {}, force: false, noPrompt: true });

    expect(fs.readFileSync(target, 'utf-8')).toEqual('MY EDITS\n');
    expect(readSync).not.toHaveBeenCalled();
  });

  test('overwrites a user-modified file under --force, without reading stdin', () => {
    const target = path.join(outputDir, 'CLAUDE.md');
    fs.writeFileSync(target, 'MY EDITS\n');
    const readSync = jest.spyOn(fs, 'readSync');

    writeGeneratedFile(outputDir, file('CLAUDE.md', 'generated\n'), { manifest: {}, force: true, noPrompt: false });

    expect(fs.readFileSync(target, 'utf-8')).toEqual('generated\n');
    expect(readSync).not.toHaveBeenCalled();
  });

  test('records manifest keys with forward slashes regardless of platform separator', () => {
    const manifest: GeneratedFileManifest = {};

    writeGeneratedFile(outputDir, file(path.join('.kiro', 'steering', 'getting-started.md'), 'body\n'), {
      manifest,
      force: false,
      noPrompt: false,
    });

    // A manifest is committed and read on other machines, so a backslash key written on
    // Windows would miss every lookup elsewhere
    expect(Object.keys(manifest)).toEqual(['.kiro/steering/getting-started.md']);
  });
});
