/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import { DataOpsProjectUtils } from '@aws-mdaa/dataops-project-l3-construct';
import { EventBridgeHelper, EventBridgeProps } from '@aws-mdaa/eventbridge-helper';
import { MdaaRole } from '@aws-mdaa/iam-constructs';
import { IMdaaKmsKey, MdaaKmsKey } from '@aws-mdaa/kms-constructs';
import { MdaaL3Construct, MdaaL3ConstructProps } from '@aws-mdaa/l3-construct';
import { Duration, IResolvable } from 'aws-cdk-lib';
import { IRule, IRuleTarget, RuleTargetConfig, RuleTargetInput } from 'aws-cdk-lib/aws-events';
import { TargetBaseProps } from 'aws-cdk-lib/aws-events-targets';
import { CfnTrigger, CfnWorkflow } from 'aws-cdk-lib/aws-glue';
import { Effect, IRole, ManagedPolicy, PolicyStatement, ServicePrincipal } from 'aws-cdk-lib/aws-iam';
import { Construct } from 'constructs';

type PropsNode = { [key: string]: unknown };

/**
 * Q-ENHANCED-INTERFACE
 * Glue workflow configuration interface for ETL orchestration with raw workflow definition and EventBridge integration. Defines workflow properties for DataOps pipeline automation including workflow definition specification and event-driven trigger configuration for complex data processing orchestration.
 *
 * Use cases: ETL workflow orchestration; Data pipeline automation; Job coordination; Event-driven workflows; DataOps automation; Multi-step data processing
 *
 * AWS: AWS Glue workflows with EventBridge integration for ETL orchestration and data pipeline automation
 *
 * Validation: rawWorkflowDef must be valid Glue workflow definition; eventBridge must be valid EventBridge configuration if specified; workflow definition must include valid jobs and triggers
 */
export interface WorkflowProps {
  /**
   * Q-ENHANCED-PROPERTY
   * Required raw workflow definition for Glue workflow configuration enabling complex ETL orchestration and job coordination. Defines the complete workflow structure including jobs, triggers, and dependencies as generated by AWS CLI, providing comprehensive workflow specification for DataOps pipeline automation.
   *
   * Use cases: ETL workflow definition; Job orchestration; Pipeline automation; Workflow structure specification; DataOps workflow configuration
   *
   * AWS: AWS Glue workflow definition with jobs, triggers, and dependencies for ETL orchestration and data pipeline automation
   *
   * Validation: Must be valid PropsNode workflow definition; required for workflow creation; must include valid jobs and triggers
   **/
  readonly rawWorkflowDef: PropsNode;
  /**
   * Q-ENHANCED-PROPERTY
   * Optional EventBridge configuration for workflow event-driven triggers enabling automated workflow execution based on external events. Defines EventBridge integration settings for triggering workflows based on S3 events, schedule patterns, or custom application events for reactive data processing.
   *
   * Use cases: Event-driven workflows; S3 event triggers; Scheduled workflow execution; External event integration; Reactive data processing
   *
   * AWS: Amazon EventBridge integration for AWS Glue workflow event-driven triggers and automated execution
   *
   * Validation: Must be valid EventBridgeProps if provided; optional for event-driven workflow triggers
   **/
  readonly eventBridge?: EventBridgeProps;
}
export interface GlueWorkflowL3ConstructProps extends MdaaL3ConstructProps {
  /**
   * Q-ENHANCED-PROPERTY
   * Required KMS key ARN for workflow resource encryption enabling customer-controlled encryption and security compliance. Provides the customer-managed KMS key for encrypting workflow resources ensuring data protection and security compliance within the DataOps workflow orchestration.
   *
   * Use cases: Resource encryption; Security compliance; Customer-controlled keys; Data protection
   *
   * AWS: KMS key ARN for Glue workflow resource encryption and customer-controlled data protection
   *
   * Validation: Must be valid KMS key ARN; required for workflow resource encryption and security compliance
   **/
  readonly kmsArn?: string;
  /**
   * Q-ENHANCED-PROPERTY
   * Required array of workflow definitions for ETL orchestration deployment enabling workflow automation and job coordination. Provides workflow specifications including job dependencies, trigger configurations, and execution logic for DataOps ETL pipeline orchestration and automation.
   *
   * Use cases: Workflow orchestration; ETL automation; Job coordination; Pipeline management
   *
   * AWS: Glue workflow definitions for ETL orchestration and pipeline automation
   *
   * Validation: Must be array of valid WorkflowProps; required for workflow deployment and ETL orchestration
   *   **/
  readonly workflowDefinitions: WorkflowProps[];
  /**
   * Q-ENHANCED-PROPERTY
   * Required security configuration name for workflow security and compliance enabling secure workflow execution and data protection. Provides the security configuration that will be used by the workflow for encryption, access control, and security compliance during workflow execution.
   *
   * Use cases: Workflow security; Security compliance; Data protection; Secure execution
   *
   * AWS: Glue security configuration for workflow security and compliance
   *
   * Validation: Must be valid security configuration name; required for workflow security and compliance
   **/
  readonly securityConfigurationName?: string;
  /**
   * Q-ENHANCED-PROPERTY
   * Required DataOps project name for workflow association and resource coordination enabling project-based resource organization and management. Provides the project identifier that associates workflows with the DataOps project for resource coordination and governance integration.
   *
   * Use cases: Project association; Resource coordination; DataOps integration; Project management
   *
   * AWS: DataOps project name for workflow association and project-based resource organization
   *
   * Validation: Must be valid project name; required for workflow project association and resource coordination
   **/
  readonly projectName: string;
}
/**
 * Customize the Lambda Event Target
 */
export interface GlueWorkflowTargetProps extends TargetBaseProps {
  /**
   * The triggering event
   */
  readonly input?: RuleTargetInput;
  /**
   * The workflow to trigger
   */
  readonly workflowArn: string;
  /**
   * The role with which to trigger the workflow
   */
  readonly role: IRole;
}

export class GlueWorkflowTarget implements IRuleTarget {
  private props: GlueWorkflowTargetProps;

  constructor(props: GlueWorkflowTargetProps) {
    this.props = props;
  }

  bind(_rule: IRule, _id?: string): RuleTargetConfig {
    console.log(`Rule: ${_rule}, id: ${_id}`);
    const retryPolicy =
      this.props.maxEventAge || this.props.retryAttempts
        ? {
            maximumEventAgeInSeconds: this.props.maxEventAge ? this.props.maxEventAge.toSeconds() : undefined,
            maximumRetryAttempts: this.props.retryAttempts,
          }
        : undefined;

    return {
      arn: this.props.workflowArn,
      role: this.props.role,
      input: this.props.input,
      deadLetterConfig: {
        arn: this.props.deadLetterQueue?.queueArn,
      },
      retryPolicy: retryPolicy,
    };
  }
}

export class GlueWorkflowL3Construct extends MdaaL3Construct {
  protected readonly props: GlueWorkflowL3ConstructProps;

  private readonly projectKmsKey: IMdaaKmsKey;
  private readonly projectName: string;

  private eventBridgePolicy?: ManagedPolicy;
  private eventBridgeRole?: IRole;

  constructor(scope: Construct, id: string, props: GlueWorkflowL3ConstructProps) {
    super(scope, id, props);
    this.props = props;
    if (!this.props.kmsArn) {
      throw new Error('Project KMS key must be defined');
    }
    this.projectKmsKey = MdaaKmsKey.fromKeyArn(this.scope, 'project-kms', this.props.kmsArn);
    this.projectName = this.props.projectName;

    // Build our workflows!
    this.props.workflowDefinitions?.map(workflowDefinition => {
      if (!this.props.securityConfigurationName) {
        throw new Error('Project Security Configuration must be defined');
      }
      const workflow = this.createWorkflowFromDefinition(workflowDefinition, this.props.securityConfigurationName);
      if (workflow.name) {
        const workflowName = (workflowDefinition.rawWorkflowDef.Workflow as PropsNode).Name;
        DataOpsProjectUtils.createProjectSSMParam(
          this.scope,
          this.props.naming,
          this.projectName,
          `workflow/name/${workflowName}`,
          workflow.name,
        );
      }
      return workflow;
    });
  }

  private getEventBridgeRole(): IRole {
    if (!this.eventBridgeRole) {
      this.eventBridgeRole = new MdaaRole(this.scope, 'event-bridge-role', {
        naming: this.props.naming,
        roleName: 'event-bridge',
        assumedBy: new ServicePrincipal('events.amazonaws.com'),
      });
    }
    return this.eventBridgeRole;
  }

  private getEventBridgePolicy(): ManagedPolicy {
    if (!this.eventBridgePolicy) {
      this.eventBridgePolicy = new ManagedPolicy(this.scope, 'event-bridge-policy', {
        managedPolicyName: this.props.naming.resourceName('event-bridge-policy'),
        roles: [this.getEventBridgeRole()],
      });
    }
    return this.eventBridgePolicy;
  }

  private createWorkflowFromDefinition(workflowProps: WorkflowProps, securityConfigurationName: string): CfnWorkflow {
    const workflowName = (workflowProps.rawWorkflowDef.Workflow as PropsNode).Name as string;
    const workflow = new CfnWorkflow(this.scope, `workflow-${workflowName}`, {
      defaultRunProperties: (workflowProps.rawWorkflowDef.Workflow as PropsNode).DefaultRunProperties,
      description: (workflowProps.rawWorkflowDef.Workflow as PropsNode).Description as string,
      name: this.props.naming.resourceName(workflowName),
    });

    const graphNodes = ((workflowProps.rawWorkflowDef.Workflow as PropsNode).Graph as PropsNode).Nodes as PropsNode[];
    const triggerProps = graphNodes.filter(node => node.Type === 'TRIGGER');

    const previousTriggers: { [key: string]: CfnTrigger } = {};
    triggerProps.forEach(triggerProps => {
      const triggerDetails = (triggerProps.TriggerDetails as PropsNode).Trigger as PropsNode;
      const triggerName = triggerDetails.Name;
      const actionsProps = triggerDetails.Actions as PropsNode[];
      const actions = actionsProps.map(actionProps =>
        this.createActionFromProps(actionProps, securityConfigurationName),
      );

      const predicateProps = triggerDetails.Predicate as PropsNode;

      const trigger = new CfnTrigger(this.scope, `trigger-${workflowName}-${triggerName}`, {
        name: this.props.naming.resourceName(`${workflowName}-${triggerName}`),
        workflowName: workflow.name,
        actions: actions,
        type: triggerDetails.Type as string,
        startOnCreation:
          triggerDetails.State && triggerDetails.State == 'ACTIVATED'
            ? true
            : (triggerDetails.StartOnCreation as IResolvable),
        predicate: predicateProps ? this.createPredicateFromProps(predicateProps) : undefined,
      });
      // If Trigger Type is Scheduled, add cron schedule to the trigger
      if (trigger.type == 'SCHEDULED') {
        trigger.schedule = triggerDetails.Schedule as string;
      }
      trigger.addDependency(workflow);

      // Force sequential deployment of Triggers by workflow, otherwise large number
      // of triggers on a single workflow will cause ConcurrentModificationExceptions.
      if (previousTriggers[workflowName]) {
        trigger.addDependency(previousTriggers[workflowName]);
      }
      previousTriggers[workflowName] = trigger;
    });

    if (workflowProps.eventBridge) {
      this.createWorkflowEventBridgeRules(workflowProps.eventBridge, workflowName);
    }

    return workflow;
  }

  private createWorkflowEventBridgeRules(eventBridgeProps: EventBridgeProps, workflowName: string) {
    const workflowResourceName = this.props.naming.resourceName(workflowName);
    const workflowArn = `arn:${this.partition}:glue:${this.region}:${this.account}:workflow/${workflowResourceName}`;
    const triggerFunctionStatement = new PolicyStatement({
      effect: Effect.ALLOW,
      actions: ['glue:notifyEvent'],
      resources: [workflowArn],
    });

    this.getEventBridgePolicy().addStatements(triggerFunctionStatement);

    const dlq = EventBridgeHelper.createDlq(
      this.scope,
      this.props.naming,
      `${workflowName}-events`,
      this.projectKmsKey,
      this.getEventBridgeRole(),
    );

    const eventBridgeRuleProps = EventBridgeHelper.createNamedEventBridgeRuleProps(eventBridgeProps, workflowName);

    Object.entries(eventBridgeRuleProps).forEach(propsEntry => {
      const ruleName = propsEntry[0];
      const ruleProps = propsEntry[1];
      const targetProps: GlueWorkflowTargetProps = {
        workflowArn: workflowArn,
        role: this.getEventBridgeRole(),
        deadLetterQueue: dlq,
        retryAttempts: eventBridgeProps.retryAttempts,
        maxEventAge: eventBridgeProps.maxEventAgeSeconds
          ? Duration.seconds(eventBridgeProps.maxEventAgeSeconds)
          : undefined,
        input: RuleTargetInput.fromObject(ruleProps.input),
      };

      const target = new GlueWorkflowTarget(targetProps);
      EventBridgeHelper.createEventBridgeRuleForTarget(this.scope, this.props.naming, target, ruleName, ruleProps);
    });
  }

  protected createPredicateFromProps(predicateProps: PropsNode): CfnTrigger.PredicateProperty {
    const conditionProps = predicateProps.Conditions as PropsNode[];
    const conditions = conditionProps.map(conditionProps => {
      return {
        crawlerName: conditionProps.CrawlerName,
        crawlState: conditionProps.CrawlState,
        jobName: conditionProps.JobName,
        logicalOperator: conditionProps.LogicalOperator,
        state: conditionProps.State,
      } as CfnTrigger.ConditionProperty;
    });
    return {
      logical: predicateProps.Logical as string,
      conditions: conditions,
    };
  }
  protected createActionFromProps(
    actionProps: PropsNode,
    securityConfigurationName: string,
  ): CfnTrigger.ActionProperty {
    const notificationProp = actionProps.NotificationProperty as PropsNode;
    return {
      arguments: actionProps.Arguments,
      crawlerName: actionProps.CrawlerName as string,
      jobName: actionProps.JobName as string,
      notificationProperty: {
        notifyDelayAfter:
          notificationProp && notificationProp.NotifyDelayAfter
            ? (notificationProp.NotifyDelayAfter as number)
            : (actionProps.Timeout as number),
      },
      securityConfiguration: securityConfigurationName,
      timeout: actionProps.Timeout as number,
    };
  }
}
