/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import { IMdaaKmsKey } from '@aws-mdaa/kms-constructs';
import { IMdaaResourceNaming } from '@aws-mdaa/naming';
import { IMdaaBucket } from '@aws-mdaa/s3-constructs';
import { DataFormat, IDatabase, Schema, S3Table } from '@aws-cdk/aws-glue-alpha';
import { CfnTrail, ReadWriteType, Trail } from 'aws-cdk-lib/aws-cloudtrail';
import { CfnTable } from 'aws-cdk-lib/aws-glue';
import { IBucket } from 'aws-cdk-lib/aws-s3';
import { Construct } from 'constructs';

/** Specifies an S3 bucket and optional object prefix for CloudTrail event selectors. */
export interface AuditEventSelector {
  /** The S3 bucket to monitor for data events. */
  readonly bucket: IBucket;
  /** Optional object prefix to scope the data events. */
  readonly objectPrefix?: string;
}

/** Read/write filter applied to a data event selector. */
export type AuditDataEventReadWriteType = 'All' | 'ReadOnly' | 'WriteOnly';

/**
 * Specifies a data event selector for any CloudTrail-supported resource type, rendered as
 * an advanced event selector. Where {@link AuditEventSelector} is S3-specific and renders
 * a basic event selector, this covers any `resources.type` CloudTrail supports (Lambda,
 * DynamoDB, Bedrock AgentCore, and so on).
 *
 * CloudTrail accepts exactly one `resources.type` per selector, so capturing N resource
 * types requires N selectors.
 */
export interface AuditDataEventSelector {
  /** Name identifying this selector on the trail. */
  readonly name: string;
  /** The CloudTrail `resources.type` whose data events will be captured. */
  readonly resourceType: string;
  /** Resource ARNs to scope the selector to. If omitted, all resources of the type are captured. */
  readonly resourceArns?: string[];
  /** Read/write filter. If omitted, both read and write events are captured. */
  readonly readWriteType?: AuditDataEventReadWriteType;
}

/**
 * Advanced event selector capturing all management events. Rendered alongside data event
 * selectors whenever management events are requested: supplying advanced event selectors
 * replaces a trail's default selectors outright, so a trail carrying only data selectors
 * would silently stop logging control plane events.
 */
const MANAGEMENT_EVENT_SELECTOR: CfnTrail.AdvancedEventSelectorProperty = {
  name: 'Management events',
  fieldSelectors: [{ field: 'eventCategory', equalTo: ['Management'] }],
};

/** `readOnly` field selector values by read/write filter. 'All' omits the selector entirely. */
const READ_ONLY_FIELD_VALUES: { readonly [readWriteType: string]: string } = {
  ReadOnly: 'true',
  WriteOnly: 'false',
};

/** Helper class for generating CloudTrail audit resources for use with S3 data events. */
export class AuditHelper {
  /**
   * Helper method which creates an S3 Data Events CloudTrail, using basic event selectors.
   *
   * For data events on any other resource type, use {@link createDataEventCloudTrail}.
   * CloudTrail accepts either basic or advanced event selectors on a trail, never both, so
   * the two styles are separate methods rather than one method with mutually exclusive args.
   *
   * @param scope The CDK scope in which the Trail resource will be created.
   * @param destinationBucket The destination bucket where the Trail will be written
   * @param encryptionKey The KMS CMK with which the trail data will be encrypted when written to S3
   * @param naming The MDAA Naming implementation which will be used to name the CloudTrail resources
   * @param trailName The name the CloudTrail. The full name will be generated by the MDAA Naming implementation
   * @param includeManagementEvents Whether to include management events in the trail
   * @param eventSelectors The set of bucket names and prefixes for which S3 data events will be captured. If not specified, the Trail will capture all S3 Data Events in the account.
   * @returns A CloudTrail which captures S3 Data Events.
   */
  public static createCloudTrail(
    scope: Construct,
    destinationBucket: IMdaaBucket,
    encryptionKey: IMdaaKmsKey,
    naming: IMdaaResourceNaming,
    trailName: string,
    includeManagementEvents?: boolean,
    eventSelectors?: AuditEventSelector[],
  ): Trail {
    const trail = this.buildTrail(scope, destinationBucket, encryptionKey, naming, trailName);

    if (eventSelectors) {
      //Add the S3 Event selectors to the Trail
      eventSelectors.forEach(selector => {
        trail.addS3EventSelector(
          [
            {
              bucket: selector.bucket,
              objectPrefix: selector.objectPrefix,
            },
          ],
          {
            includeManagementEvents: includeManagementEvents != undefined && includeManagementEvents,
            readWriteType: ReadWriteType.ALL,
          },
        );
      });
    } else {
      trail.logAllS3DataEvents({
        includeManagementEvents: includeManagementEvents != undefined && includeManagementEvents,
        readWriteType: ReadWriteType.ALL,
      });
    }

    return trail;
  }

  /**
   * Helper method which creates a CloudTrail capturing data events for any CloudTrail-supported
   * resource type, using advanced event selectors.
   *
   * The L2 Trail construct does not expose advanced event selectors, so these are applied to the
   * underlying CfnTrail via an escape hatch, leaving KMS wiring, nag suppressions, and the
   * returned type identical to {@link createCloudTrail}.
   *
   * @param scope The CDK scope in which the Trail resource will be created.
   * @param destinationBucket The destination bucket where the Trail will be written
   * @param encryptionKey The KMS CMK with which the trail data will be encrypted when written to S3
   * @param naming The MDAA Naming implementation which will be used to name the CloudTrail resources
   * @param trailName The name the CloudTrail. The full name will be generated by the MDAA Naming implementation
   * @param dataEventSelectors The resource types for which data events will be captured. One selector is rendered per entry.
   * @param includeManagementEvents Whether to also capture management events. Advanced event selectors replace a trail's defaults entirely, so without this the trail captures no control plane events at all.
   * @returns A CloudTrail which captures the requested Data Events.
   */
  public static createDataEventCloudTrail(
    scope: Construct,
    destinationBucket: IMdaaBucket,
    encryptionKey: IMdaaKmsKey,
    naming: IMdaaResourceNaming,
    trailName: string,
    dataEventSelectors: AuditDataEventSelector[],
    includeManagementEvents?: boolean,
  ): Trail {
    const trail = this.buildTrail(scope, destinationBucket, encryptionKey, naming, trailName);

    const dataSelectors = dataEventSelectors.map(selector => this.buildDataEventSelector(selector));
    const advancedEventSelectors = includeManagementEvents
      ? [MANAGEMENT_EVENT_SELECTOR, ...dataSelectors]
      : dataSelectors;

    // CDK still emits an empty basic EventSelectors list, which CloudTrail rejects alongside
    // advanced selectors, so that property is removed rather than left to deploy and fail.
    const cfnTrail = trail.node.defaultChild as CfnTrail;
    cfnTrail.advancedEventSelectors = advancedEventSelectors;
    cfnTrail.addPropertyDeletionOverride('EventSelectors');

    return trail;
  }

  /**
   * Creates the Trail itself, shared by both selector styles.
   * @param scope The CDK scope in which the Trail resource will be created.
   * @param destinationBucket The destination bucket where the Trail will be written
   * @param encryptionKey The KMS CMK with which the trail data will be encrypted when written to S3
   * @param naming The MDAA Naming implementation which will be used to name the CloudTrail resources
   * @param trailName The name of the CloudTrail, before MDAA naming is applied
   * @returns The created Trail, with no event selectors applied.
   */
  private static buildTrail(
    scope: Construct,
    destinationBucket: IMdaaBucket,
    encryptionKey: IMdaaKmsKey,
    naming: IMdaaResourceNaming,
    trailName: string,
  ): Trail {
    return new Trail(scope, `audit-trail-${trailName}`, {
      trailName: naming.resourceName(trailName),
      bucket: destinationBucket,
      encryptionKey: encryptionKey,
      isMultiRegionTrail: false,
      includeGlobalServiceEvents: false,
    });
  }

  /**
   * Builds a single advanced event selector for a data event selector config.
   *
   * `resources.ARN` is matched with `StartsWith` rather than `Equals` so that a parent resource
   * ARN also captures events recorded against its children -- an AgentCore runtime endpoint ARN,
   * for example, is prefixed by its runtime ARN. `Equals` would require every child ARN listed.
   *
   * @param selector The data event selector config to render.
   * @returns The rendered advanced event selector.
   */
  private static buildDataEventSelector(selector: AuditDataEventSelector): CfnTrail.AdvancedEventSelectorProperty {
    // `equalTo` is CDK's name for the CloudFormation `Equals` operator.
    const fieldSelectors: CfnTrail.AdvancedFieldSelectorProperty[] = [
      { field: 'eventCategory', equalTo: ['Data'] },
      { field: 'resources.type', equalTo: [selector.resourceType] },
    ];

    if (selector.resourceArns && selector.resourceArns.length > 0) {
      fieldSelectors.push({ field: 'resources.ARN', startsWith: selector.resourceArns });
    }

    const readOnlyValue = selector.readWriteType ? READ_ONLY_FIELD_VALUES[selector.readWriteType] : undefined;
    if (readOnlyValue) {
      fieldSelectors.push({ field: 'readOnly', equalTo: [readOnlyValue] });
    }

    return { name: selector.name, fieldSelectors: fieldSelectors };
  }

  /**
   * A helper method for generating a Glue table for querying CloudTrail audit events from an S3 bucket.
   * @param scope The scope in which the table will be created.
   * @param bucket The bucket where the CloudTrail data is stored
   * @param database The database where the table will be created
   * @param accounts The accounts for which CloudTrail data has been produced in the bucket.
   * @param regions The regions for which CloudTrail data has been produced in the bucket.
   * @returns A Glue Table which can be used to query CloudTrail data.
   */
  public static createGlueAuditTable(
    scope: Construct,
    bucket: IMdaaBucket,
    database: IDatabase,
    accounts: string[],
    regions: string[],
  ): S3Table {
    const location = `s3://${bucket.bucketName}/AWSLogs`;
    const cloudTrailTable = new S3Table(scope, 'CloudTrailGlueTable', {
      columns: [
        { name: 'eventversion', type: Schema.STRING },
        {
          name: 'useridentity',
          type: Schema.struct([
            { name: 'type', type: Schema.STRING },
            { name: 'principalid', type: Schema.STRING },
            { name: 'arn', type: Schema.STRING },
            { name: 'accountid', type: Schema.STRING },
            { name: 'invokedby', type: Schema.STRING },
            { name: 'accesskeyid', type: Schema.STRING },
            { name: 'userName', type: Schema.STRING },
            {
              name: 'sessioncontext',
              type: Schema.struct([
                {
                  name: 'attributes',
                  type: Schema.struct([
                    { name: 'mfaauthenticated', type: Schema.STRING },
                    { name: 'creationdate', type: Schema.STRING },
                  ]),
                },
                {
                  name: 'sessionissuer',
                  type: Schema.struct([
                    { name: 'type', type: Schema.STRING },
                    { name: 'principalId', type: Schema.STRING },
                    { name: 'arn', type: Schema.STRING },
                    { name: 'accountId', type: Schema.STRING },
                    { name: 'userName', type: Schema.STRING },
                  ]),
                },
              ]),
            },
          ]),
        },
        { name: 'eventtime', type: Schema.STRING },
        { name: 'eventsource', type: Schema.STRING },
        { name: 'eventname', type: Schema.STRING },
        { name: 'awsregion', type: Schema.STRING },
        { name: 'sourceipaddress', type: Schema.STRING },
        { name: 'useragent', type: Schema.STRING },
        { name: 'errorcode', type: Schema.STRING },
        { name: 'errormessage', type: Schema.STRING },
        { name: 'requestparameters', type: Schema.STRING },
        { name: 'responseelements', type: Schema.STRING },
        { name: 'additionaleventdata', type: Schema.STRING },
        { name: 'requestid', type: Schema.STRING },
        { name: 'eventid', type: Schema.STRING },
        {
          name: 'resources',
          type: Schema.array(
            Schema.struct([
              { name: 'ARN', type: Schema.STRING },
              { name: 'accountId', type: Schema.STRING },
              { name: 'type', type: Schema.STRING },
            ]),
          ),
        },
        { name: 'eventtype', type: Schema.STRING },
        { name: 'apiversion', type: Schema.STRING },
        { name: 'readonly', type: Schema.STRING },
        { name: 'recipientaccountid', type: Schema.STRING },
        { name: 'serviceeventdetails', type: Schema.STRING },
        { name: 'sharedeventid', type: Schema.STRING },
        { name: 'vpcendpointid', type: Schema.STRING },
      ],
      dataFormat: DataFormat.CLOUDTRAIL_LOGS,
      database: database,
      tableName: 'cloudtrail_audit',
      bucket: bucket,
      description: 'CloudTrail Glue table',
      s3Prefix: `AWSLogs`,
      partitionKeys: [
        { name: 'timestamp', type: Schema.STRING },
        { name: 'region', type: Schema.STRING },
        { name: 'account', type: Schema.STRING },
      ],
    });
    const cfnTable = cloudTrailTable.node.defaultChild as CfnTable;
    cfnTable.addOverride('Properties.TableInput.Parameters', {
      EXTERNAL: 'TRUE',
      'projection.enabled': 'true',
      'projection.timestamp.type': 'date',
      'projection.timestamp.range': '2021/01/01,NOW',
      'projection.timestamp.format': 'yyyy/MM/dd',
      'projection.timestamp.interval': '1',
      'projection.timestamp.interval.unit': 'DAYS',
      'projection.account.type': 'enum',
      'projection.account.values': accounts.join(','),
      'projection.region.type': 'enum',
      'projection.region.values': regions.join(','),
      'storage.location.template': location + '/${account}/CloudTrail/${region}/${timestamp}',
    });
    return cloudTrailTable;
  }
}
