# The list of Lake Formation Admin role references
lakeFormationAdminRoles: []

# If true, LakeFormation will add IAM_ALLOWED_PRINCIPALS
# permission by default to all new databases and tables.
# This results in LakeFormation deferring to IAM permissions
# which may have been granted via IAM policies directly against
# Glue catalog resources.
# If false (default), permissions must be explicitly granted in
# IAM policies (coarse-grained), and in LakeFormation grants (fine-grained).
iamAllowedPrincipalsDefault: true
