AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an EC2 instance accessible via SSM with 100GB storage'

Parameters:
  InstanceType:
    Type: String
    Default: m5.2xlarge
    Description: EC2 instance type
  
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
    Description: SSM parameter for the latest Amazon Linux 2023 AMI

Resources:
  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref SSMInstanceRole

  SSMInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref SSMInstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 100
            VolumeType: gp3
            DeleteOnTermination: true
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          # Update system and install required packages
          dnf update -y
          dnf install -y docker git make
          systemctl enable docker
          systemctl start docker
          
          # Install n (Node version manager)
          git clone https://github.com/tj/n /tmp/n
          cd /tmp/n && make install
          
          # Install Node.js 22.13.1
          n 22.13.1
          
          # Install global npm packages
          npm install --save-dev -g -f grunt grunt-cli webpack yarn
          
          # Update npm to specific version
          npm install -g npm@10.9.2
          
          # Clean up
          rm -rf /tmp/n
          
          # Pull CodeBuild image instead of building it
          docker pull public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:5.0

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group with no inbound access
      SecurityGroupIngress: []  # No inbound rules - access only via SSM

Outputs:
  InstanceId:
    Description: ID of the EC2 instance
    Value: !Ref EC2Instance
  SSMSessionCommand:
    Description: Command to start SSM session
    Value: !Sub "aws ssm start-session --target ${EC2Instance}"
