"""
This script is an example of code that can be used to create an AWS Glue custom visual transform
to post data quality results generated by AWS Glue DataQuality in an ETL job to Amazon SageMakerUnifiedStudio.

Dependencies:
- boto3 (AWS SDK for Python)
- awsglue (AWS Glue Python library)
- re (Python regular expression module)
- json (Python JSON module)
- datetime (Python datetime module)

Version: 1.0
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
"""

import json
import logging
import re
from datetime import datetime

import boto3
from awsglue import DynamicFrame

logger = logging.getLogger(__name__)


def post_dq_results(
    df: DynamicFrame,
    domain_id: str,
    asset_source_id: str,
    dq_ruleset_name: str,
    asset_ids: [str] = [],
    role_to_assume: str | None = None,
) -> str:
    """
    Post data quality results to Amazon SageMakerUnifiedStudio.

    Args:
        df (DynamicFrame) : The instance of the class on which this method is called.
        role_to_assume (str): The ARN of the IAM role to assume.
        domain_id (str): The Amazon SageMakerUnifiedStudio domain identifier.
        asset_source_id (str): The SMUS Asset Source Identifier of the table.
        dq_ruleset_name (str): The name of the ruleset.

    Returns:
        str: A success or error message.
    """

    logger.info(
        f"Starting post data quality results to SageMakerUnifiedStudio... {DynamicFrame=}"
    )
    try:
        # Get the data quality results from the DynamicFrame
        df = df.toDF()
        dq_results = df.collect()

        logger.info(f"Data quality results: {dq_results}")

        # Create the Amazon SageMakerUnifiedStudio client
        smus_client = create_smus_client(role_to_assume)
        logger.info("SageMakerUnifiedStudio Client ready!")

        # Search for the asset ID
        asset_ids += search_asset_id(smus_client, domain_id, asset_source_id)

        logger.info(f"list pf entity identifiers: {asset_ids}")

        if asset_ids is None:
            raise DataQualityJobError(
                f"Error error no asset found, {asset_source_id=}, {asset_ids=}"
            )
        else:
            # Post the data quality results to Amazon SageMakerUnifiedStudio
            ts_form = generate_ts_form(dq_results, dq_ruleset_name)
            response = post_data_quality_results(
                smus_client, domain_id, asset_ids, ts_form
            )
            logger.info(f"Data quality results posted successfully: {response}")
            return df
    except Exception as e:
        raise DataQualityJobError(f"Error calling post data quality results: {e}")


class DataQualityJobError(Exception):
    """
    Custom exception class for errors related to the data quality job.
    """

    pass


def create_smus_client(role_to_assume: str | None) -> boto3.client:
    """
    Create an Amazon SageMakerUnifiedStudio client with the specified role.

    Args:
        role_to_assume (str): The ARN of the IAM role to assume.

        This parameter is needed when running cross accounts and is used to assume a different role in the SageMakerUnifiedStudio Domain Account for the client.
        The reason why we need to assume a different role is because the SageMakerUnifiedStudio post_time_series_data_points does not
        yet support cross account writes. When the cross account write will be supported for the API we can simplify the
        method and remove this parameter.

    Returns:
        boto3.client: The Amazon SageMakerUnifiedStudio client.
    """
    try:
        credentials = get_credential_for_role(role_to_assume)
        if not credentials:
            # Create the SageMakerUnifiedStudio client with the local role
            return boto3.client("datazone")
        else:
            # Create the SageMakerUnifiedStudio client with the assumed role credentials
            return boto3.client(
                service_name="datazone",
                region_name=get_current_region(),
                aws_access_key_id=credentials["AccessKeyId"],
                aws_secret_access_key=credentials["SecretAccessKey"],
                aws_session_token=credentials["SessionToken"],
            )
    except Exception:
        logger.exception("Error creating SageMakerUnifiedStudio client")
        raise DataQualityJobError("Error creating SageMakerUnifiedStudio client")


def get_credential_for_role(role_to_assume: str | None) -> dict:
    """
    Validate the format of an Amazon Resource Name (ARN).

    Args:
        arn_str (str): The ARN string to validate.

    Returns:
        dict: Dictionary containing the temporary credentials for the assumed role.
    """
    if role_to_assume:
        try:
            # Assume the specified IAM role in the domain account
            sts = boto3.client("sts", region_name=get_current_region())
            assumed_role_object = sts.assume_role(
                RoleArn=role_to_assume, RoleSessionName="AssumeRoleSession"
            )
            return assumed_role_object["Credentials"]
        except Exception as e:
            raise DataQualityJobError(f"Error assuming {role_to_assume=}\n{e}")


def get_current_region() -> str:
    """
    Get the current AWS region.

    Returns:
        str: The current AWS region.
    """
    try:
        session = boto3.Session()
        return session.region_name
    except Exception:
        logger.exception("Error getting current region")
        raise DataQualityJobError("Error getting current region")


def search_asset_id(smus_client, domain_id, asset_source_id) -> list:
    """
    Search for an asset in Amazon SageMakerUnifiedStudio.

    Args:
        smus_client (boto3.client): The Amazon SageMakerUnifiedStudio client.
        domain_id (str): The domain identifier.
        asset_source_id (str): The SMUS asset source identifier.
    Returns:
        list: The list of entity identifiers for the asset, or None if not found.
    """
    logger.info(f"starting search ... ")
    entity_identifier_list = []
    if not asset_source_id:
        return entity_identifier_list
    try:
        paginator = smus_client.get_paginator("search_listings")
        # The DataZone search_listings API does not support filtering by
        # sourceIdentifier server-side. Currently fetches all listings and filters client-side,
        # which is inefficient for domains with many assets. Revisit when the API adds filter support.
        for page in paginator.paginate(
            additionalAttributes=["FORMS"], domainIdentifier=domain_id
        ):
            for item in page["items"]:
                forms_dict = json.loads(
                    item["assetListing"]["additionalAttributes"]["forms"]
                )
                if (
                    forms_dict.get("AssetCommonDetailsForm", {}).get(
                        "sourceIdentifier", None
                    )
                    == asset_source_id
                ):
                    entity_identifier = item["assetListing"]["entityId"]
                    logger.info(f"SMUS Asset Id: {entity_identifier}")
                    entity_identifier_list.append(entity_identifier)

        logger.info(f"SMUS Asset Id list: {entity_identifier_list}")
        return entity_identifier_list
    except Exception:
        logger.exception("Error searching for asset ID")
        raise DataQualityJobError("Error searching for asset ID")


def generate_ts_form(results, dq_ruleset_name) -> dict:
    """
    Generate the time series form for posting to Amazon SageMakerUnifiedStudio.

    Args:
        results (list): A list of evaluation objects.

    Returns:
        dict: The time series form dictionary.
    """
    try:
        ts_form = {
            "content": json.dumps(
                {
                    "evaluationsCount": len(results),
                    "evaluations": [
                        process_evaluation(evaluation) for evaluation in results
                    ],
                    "passingPercentage": calculate_score(results),
                }
            ),
            "formName": dq_ruleset_name,  # Specify your desired Ruleset Name
            "typeIdentifier": "amazon.datazone.DataQualityResultFormType",
            "timestamp": datetime.now().timestamp(),
        }

        logger.info(f"Generated time series form: {json.dumps(ts_form, default=str)}")
        return ts_form
    except Exception:
        logger.exception("Error generating time series form")
        raise DataQualityJobError("Error generating time series form")


def process_evaluation(evaluation) -> dict:
    """
    Process the evaluation results and extract relevant information.

    Args:
        evaluation (object): An evaluation object containing the rule, metrics, and outcome.

    Returns:
        dict: A dictionary containing the processed evaluation information.
    """
    try:
        result = {}
        evaluation_detail_type = "EVALUATION_MESSAGE"
        result_value = evaluation.FailureReason

        # Extract rule, metric types, and columns from the evaluation
        rule, metric_types, columns = extract_metadata(
            evaluation.Rule, evaluation.EvaluatedMetrics
        )

        evaluation_details = (
            {evaluation_detail_type: result_value} if result_value else {}
        )

        result = {
            "applicableFields": columns,
            "types": metric_types,
            "status": "PASS" if evaluation.Outcome == "Passed" else "FAIL",
            "description": f"{rule}",
            "details": evaluation_details,
        }

        logger.info(f"Processed evaluation: {result}")

        return result
    except Exception:
        logger.exception("Error processing evaluation")
        raise DataQualityJobError("Error processing evaluation")


def extract_metadata(rule, evaluated_metrics):
    """
    Extract information on rule, metric types, and columns from the evaluation.

    Args:
        rule (str): The rule description.
        evaluated_metrics (dict): The evaluated metrics.

    Returns:
        tuple: A tuple containing the rule, metric types, and columns.
    """
    try:
        metric_types = [key.split(".")[-1] for key in evaluated_metrics]
        columns = re.findall(r'"(.*?)"', rule)

        logger.info(
            f"Extracted metadata: rule={rule}, metric_types={metric_types}, columns={columns}"
        )
        return rule, metric_types, columns
    except Exception:
        logger.exception("Error extracting metadata")
        raise DataQualityJobError("Error extracting metadata")


def calculate_score(results) -> float:
    """
    Calculate the score based on the number of successful evaluations.

    Args:
        results (list): A list of evaluation objects.

    Returns:
        float: The calculated score as a percentage.
    """
    try:
        num_success = sum(1 for evaluation in results if evaluation.Outcome == "Passed")
        total_results = len(results)

        score = (num_success / total_results) * 100 if total_results else 0.0
        logger.info(f"Calculated score: {score}%")
        return score
    except Exception:
        logger.exception("Error calculating score")
        raise DataQualityJobError("Error calculating score")


def post_data_quality_results(smus_client, domain_id, asset_ids, ts_form) -> dict:
    """
    Post data quality time series data points to Amazon SageMaker Unified Studio.

    Args:
        smus_client (boto3.client): The Amazon SageMaker Unified Studio client.
        entity_identifier (str): The asset identifier.
        ts_form (dict): The time series form dictionary.

    Returns:
        List of dict: The list of responses from each of the post_time_series_data_points API call.
    """
    response_list = []
    for asset_id in asset_ids:
        try:
            response = smus_client.post_time_series_data_points(
                domainIdentifier=domain_id,
                entityIdentifier=asset_id,
                entityType="ASSET",
                forms=[ts_form],
            )

            logger.info(f"Posted results: {json.dumps(response, default=str)}")
            response_list.append(response)
        except Exception:
            logger.exception(f"Error posting data quality results to {asset_id=}")
            raise DataQualityJobError(
                f"Error posting data quality results to {asset_id=}"
            )
    return response_list
