import { IConstruct } from 'constructs';
import { MdaaNagSuppressions } from '@aws-mdaa/construct';
import { AppSyncLambdaDataSource, Code, EventApi, LambdaInvokeType } from 'aws-cdk-lib/aws-appsync';
import * as path from 'node:path';
import { MdaaLambdaFunction } from '@aws-mdaa/lambda-constructs';
import { MdaaL3Construct } from '@aws-mdaa/l3-construct';

/**
 * Adds a data source to an AppSync Event API channel namespace for WebSocket routing.
 *
 * This function configures the WebSocket message routing by:
 * - Creating a channel namespace for the data source
 * - Configuring direct Lambda invocation for real-time processing
 * - Setting up event-based invocation for asynchronous processing
 * - Loading the namespace handler code for message routing
 *
 * @param id - Unique identifier for the channel namespace
 * @param eventApi - AppSync Event API instance
 * @param dataSource - Lambda data source to associate with the namespace
 * @param channelNamespaceName - Name of the channel namespace for routing
 */

export function addDataSourceToChannelNamespace(
  id: string,
  eventApi: EventApi,
  dataSource: AppSyncLambdaDataSource,
  channelNamespaceName: string,
) {
  eventApi.addChannelNamespace(id, {
    channelNamespaceName: channelNamespaceName,
    publishHandlerConfig: {
      // direct: true bypasses resolver logic, sending messages directly to Lambda
      direct: true,
      dataSource: dataSource,
      // EVENT invocation is async (fire-and-forget) - AppSync doesn't wait for Lambda response.
      // The Lambda streams responses back to the client via the WebSocket API (WEB_SOCKET_URL).
      // This enables long-running operations and streaming without AppSync timeout constraints.
      lambdaInvokeType: LambdaInvokeType.EVENT,
    },
    // Load the namespace handler code for message routing
    code: Code.fromAsset(path.join(__dirname, '../../namespace/in/index.js')),
  });
}

/**
 * Applies CDK Nag suppressions for data source constructs.
 *
 * These suppressions address common compliance warnings for:
 * - IAM wildcard permissions for dynamic log stream names and DynamoDB index ARNs
 *   (granted via table.grantReadWriteData()/grantReadData())
 * - Inline policies automatically generated by CDK
 *
 * Regarding inline policies: When CDK creates IAM roles for Lambda functions and grants
 * permissions (e.g., DynamoDB access via table.grantReadWriteData()), it automatically
 * generates inline policies attached to the role. These are scoped to specific resources
 * and are not reusable across roles, which is why CDK uses inline policies rather than
 * managed policies. This is standard CDK behavior and the policies are appropriately scoped.
 */
export function addNagSuppressionsForDataSource(dataSourceConstruct: MdaaL3Construct) {
  MdaaNagSuppressions.addCodeResourceSuppressions(
    dataSourceConstruct,
    [
      {
        id: 'AwsSolutions-IAM5',
        reason:
          'Wildcards scoped to: (1) LogStream names dynamically generated by Lambda — the wildcard is limited to the ' +
          'log stream segment of the CloudWatch Logs ARN and cannot be enumerated at deployment time, ' +
          'and (2) DynamoDB index ARNs (<tableArn>/index/*) granted via table.grantReadWriteData()/grantReadData().',
      },
      {
        id: 'NIST.800.53.R5-IAMNoInlinePolicy',
        reason:
          'Inline policy is auto-generated by CDK grant methods (table.grantReadWriteData(), layer.grantUsage(), etc.) and ' +
          'is scoped to the specific Lambda execution role for this data source. CDK grant helpers emit inline policies by ' +
          'design because the policy document references identifiers created within the same stack and is not intended for ' +
          'reuse across roles (https://docs.aws.amazon.com/cdk/v2/guide/permissions.html).',
      },
      {
        id: 'HIPAA.Security-IAMNoInlinePolicy',
        reason:
          'Inline policy is auto-generated by CDK grant methods (table.grantReadWriteData(), layer.grantUsage(), etc.) and ' +
          'is scoped to the specific Lambda execution role for this data source. CDK grant helpers emit inline policies by ' +
          'design because the policy document references identifiers created within the same stack and is not intended for ' +
          'reuse across roles (https://docs.aws.amazon.com/cdk/v2/guide/permissions.html).',
      },
      {
        id: 'PCI.DSS.321-IAMNoInlinePolicy',
        reason:
          'Inline policy is auto-generated by CDK grant methods (table.grantReadWriteData(), layer.grantUsage(), etc.) and ' +
          'is scoped to the specific Lambda execution role for this data source. CDK grant helpers emit inline policies by ' +
          'design because the policy document references identifiers created within the same stack and is not intended for ' +
          'reuse across roles (https://docs.aws.amazon.com/cdk/v2/guide/permissions.html).',
      },
    ],
    true,
  );
}

/**
 * Applies CDK Nag suppressions for Lambda functions used in WebSocket data sources.
 *
 * These suppressions address:
 * - Dead Letter Queue requirements (not needed for synchronous API functions)
 * - Concurrency limits (conditionally applied based on configuration)
 * - Security compliance for different frameworks (NIST, HIPAA, PCI DSS)
 *
 * @param websocketHandler - Lambda function to apply suppressions to
 * @param configuredReservedConcurrentExecutions - Reserved concurrency configuration
 */
export function addNagSuppressionsRuleForDataSourceLambdaFunction(
  websocketHandler: MdaaLambdaFunction,
  configuredReservedConcurrentExecutions: number | undefined,
) {
  // Apply suppressions for DLQ requirements (errors handled internally by publishing back to WebSocket client)
  MdaaNagSuppressions.addCodeResourceSuppressions(
    websocketHandler,
    [
      { id: 'AwsSolutions-L1', reason: 'Runtime version is pinned for stability.' },
      {
        id: 'NIST.800.53.R5-LambdaDLQ',
        reason:
          'Function is invoked asynchronously via AppSync Events (LambdaInvokeType.EVENT). ' +
          'Errors are handled within the Lambda by publishing error messages back to the WebSocket client, making a DLQ unnecessary.',
      },
      {
        id: 'HIPAA.Security-LambdaDLQ',
        reason:
          'Function is invoked asynchronously via AppSync Events (LambdaInvokeType.EVENT). ' +
          'Errors are handled within the Lambda by publishing error messages back to the WebSocket client, making a DLQ unnecessary.',
      },
      {
        id: 'PCI.DSS.321-LambdaDLQ',
        reason:
          'Function is invoked asynchronously via AppSync Events (LambdaInvokeType.EVENT). ' +
          'Errors are handled within the Lambda by publishing error messages back to the WebSocket client, making a DLQ unnecessary.',
      },
    ],
    true,
  );

  // Apply concurrency suppressions only if reserved concurrency is not configured (user configuration)
  if (configuredReservedConcurrentExecutions === undefined) {
    MdaaNagSuppressions.addCodeResourceSuppressions(
      websocketHandler,
      [
        {
          id: 'NIST.800.53.R5-LambdaConcurrency',
          reason: 'Datasource configured to not use ReservedConcurrentExecutions.',
        },
        {
          id: 'HIPAA.Security-LambdaConcurrency',
          reason: 'Datasource configured to not use ReservedConcurrentExecutions.',
        },
        {
          id: 'PCI.DSS.321-LambdaConcurrency',
          reason: 'Datasource configured to not use ReservedConcurrentExecutions.',
        },
      ],
      true,
    );
  }
}

/**
 * Applies CDK Nag suppressions for AppSync service roles.
 *
 * These suppressions address IAM policy warnings for:
 * - IAM5 wildcard: appsync:* actions scoped to the specific Lambda function ARN,
 *   granted by CDK's addLambdaDataSource()
 * - Inline policies automatically generated by CDK for AppSync-to-Lambda integration
 *
 * @param dataSource - AppSync data source construct to apply suppressions to
 */
export function addNagSuppressionsRuleForAppSyncRole(dataSource: IConstruct) {
  MdaaNagSuppressions.addCodeResourceSuppressions(
    dataSource,
    [
      {
        id: 'AwsSolutions-IAM5',
        reason:
          'Wildcard actions (appsync:*) are scoped to the specific Lambda function ARN and granted by ' +
          'CDK addLambdaDataSource(). This is required for AppSync Event API to invoke the data source Lambda.',
      },
      {
        id: 'NIST.800.53.R5-IAMNoInlinePolicy',
        reason:
          'Inline policy is auto-generated by CDK addLambdaDataSource() to grant AppSync Event API ' +
          'invoke permissions on the specific Lambda function ARN.',
      },
      {
        id: 'HIPAA.Security-IAMNoInlinePolicy',
        reason:
          'Inline policy is auto-generated by CDK addLambdaDataSource() to grant AppSync Event API ' +
          'invoke permissions on the specific Lambda function ARN.',
      },
      {
        id: 'PCI.DSS.321-IAMNoInlinePolicy',
        reason:
          'Inline policy is auto-generated by CDK addLambdaDataSource() to grant AppSync Event API ' +
          'invoke permissions on the specific Lambda function ARN.',
      },
    ],
    true,
  );
}
